### ISSUE TITLE
[ISSUE] Using Acra as proxy/encryptor with rails app fails to encrypt

### ISSUE THREAD

**Issue by arffsaad** [cossacklabs/acra#585]
**Describe the bug**
I have used acra for my own projects with both mysql and postgres and it works like a charm. Now i am trying to encrypt the database (PostgreSQL) of a chat app based on rails (chatwoot) but it seems like encryption doesn't seem to work at all. 

The error that comes is written as:
`time="2022-09-28T06:57:05Z" level=error msg="Column count in RowDescription packet not same as parsed query count of columns`

**To Reproduce**
1. Install chatwoot (preferably not the docker version)
2. Setup acra server and encryptor config (i followed the example configs very closely) and include one table + one column from it.
3. Start acra (at this point the error logs already pop off)
4. Data can be shown and inserted, but it is not encrypted.

**Expected behavior**
Acra does not show this error, and chatwoot data is encrypted succesfully with no issues.

**Acra configuration files**
For AcraServer: 
acra-server.yaml
```
version: 0.93.0
client_id: dbEncrypt
mysql_enable: false
postgresql_enable: true
db_port: 5432
db_host: 127.0.0.1
zonemode_enable: false
encryptor_config_file: "/etc/acra/acra-encryptor.yaml"
```

acra-encryptor.yaml

```
defaults:
  crypto_envelope: acrablock

schemas:
- table: users
  columns:
    - id
    - provider
    - uid
    - encrypted_password
    - reset_password_token
    - reset_password_sent_at
    - remember_created_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - confirmation_token
    - confirmed_at
    - confirmation_sent_at
    - unconfirmed_email
    - name
    - display_name
    - email
    - tokens
    - created_at
    - updated_at
    - pubsub_token
    - availability
    - ui_settings
    - custom_attributes
    - type
    - message_signature
  encrypted:
  - column: name
    token_type: str
    tokenized: true
```
**Environment:**
- Acra version: [e.g. 0.93.0]
- Database server and its version: [PostgreSQL 10.21]
- Installed components:
   - [x] AcraServer
- Data-in-transit encryption between Acra and the client-side application:
   - [x] no transport encryption (Transparent Encryption)
- Installation way:
   - [x] From source.

**Comment by Lagovas** [comment]
```
encrypted:
  - column: name
    token_type: str
    tokenized: true
```
with these settings acra-server will tokenize data instead of encryption. so in your database you should expect replaced data instead of real data that you try to store.

I'm not familiar with chatwoot, so it requires more time to reproduce this case.
Will be much better if you show whole logs from acra-server, not only one error row. And try to start acra-server with `-d` flag that turns on debug level logs before it.
