### ISSUE TITLE
"invalid encryptor config" Using response_on_fail Option on Encryptor Config

### ISSUE THREAD

**Issue by rojinebrahimi** [cossacklabs/acra#714]
Hey! I got an issue with the encryptor config where defining `response_on_fail` option makes the whole configuration invalid.
Here is the configuration:
```
database_settings:
defaults:
  crypto_envelope: "acrablock"
schemas:
- columns:
  - id
  - email
  - name
  encrypted:
  - column: email
    response_on_fail: error
    searchable: true
  table: mytable
```
Here is the result:
![Screenshot 2024-09-01 at 20 00 30](https://github.com/user-attachments/assets/8c6c795e-f61f-4b8d-9d41-7ae4fd8f11b4)

- Acra version: 0.95.0
- Database server and its version: MariaDB 11.4.3 
- Installed components:
   - [x] AcraServer
   - [ ] AcraTranslator
- Data-in-transit encryption between Acra and the client-side application:
   - [ ] TLS
   - [ ] AcraConnector
   - [x] no transport encryption
- Installation way:
   - [x] via Docker
   - [ ] via package manager

Thanks in advance!
